// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "ad8bb31c-367b-400c-affa-d2f0005dd121");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1578699152);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1578699272);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578702428);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1578698912);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1578698792);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1578699032);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578699512);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1578699392);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 50556);
user_pref("browser.cache.disk.capacity", 204800);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578698642);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4a2624ad-044f-462c-923f-55c82e5fe204}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578702578928");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578704388928");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578702422245");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578706022245");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190718161435");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1578700319");
user_pref("browser.slowStartup.averageTime", 11186);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1578700315);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578698664960");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "a8de252f252b48eb9eb214ca44516b29");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 10 Jan 2020 11:47:45 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1578699153);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190718161435");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{cce89ce5-0a56-4b52-a2b9-56ee3cfc9191}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"6.1.0\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"bcd737e9-ae71-41f0-ad32-8dd7a596342c\",\"fxmonitor@mozilla.org\":\"d3e907d4-135b-4193-95cc-429b906c33a1\",\"screenshots@mozilla.org\":\"e04b9e4f-39b2-4668-bd28-cb7539015b33\",\"webcompat-reporter@mozilla.org\":\"9c9c26ff-e4f7-43a1-a002-73b10e838f9f\",\"webcompat@mozilla.org\":\"25045a5e-dc00-41fb-a74e-1c72588db3a0\",\"default-theme@mozilla.org\":\"c8d0dd34-b49f-4ebc-846e-3527a44dae10\",\"google@search.mozilla.org\":\"83e296e6-a4ed-4fbd-bb5d-cd5b4fe81d0e\",\"amazondotcom@search.mozilla.org\":\"8948491c-aaaa-4e0a-b11b-3bfe4a755345\",\"bing@search.mozilla.org\":\"a32e4c0d-e3d0-496f-a858-88e9de5feb3c\",\"ddg@search.mozilla.org\":\"7722ae7b-9f61-4f60-a63b-b94dde073655\",\"ebay@search.mozilla.org\":\"37ba7cee-06c3-4af8-b85d-86628f4bf0d6\",\"twitter@search.mozilla.org\":\"29aaee66-7faf-4733-bac7-3dd16468cd11\",\"wikipedia@search.mozilla.org\":\"985e0eb0-5095-4ee0-9da8-4956f51bb36f\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1578699177);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1578698824);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1578698823);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1578699177);
user_pref("places.history.expiration.transient_current_max_pages", 47953);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "b9b870ef-c251-40fb-bcee-b2eb1562cda6");
user_pref("security.sandbox.plugin.tempDirSuffix", "b7adacea-2d63-4b0a-b5ba-be6b9028c2db");
user_pref("services.blocklist.pinning.checked", 1578701073);
user_pref("services.settings.clock_skew_seconds", -69);
user_pref("services.settings.last_etag", "\"1578700819498\"");
user_pref("services.settings.last_update_seconds", 1578702061);
user_pref("services.settings.main.cfr-fxa.last_check", 1578701073);
user_pref("services.settings.main.cfr.last_check", 1578701073);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1578701073);
user_pref("services.settings.main.hijack-blocklists.last_check", 1578701073);
user_pref("services.settings.main.language-dictionaries.last_check", 1578701073);
user_pref("services.settings.main.normandy-recipes.last_check", 1578701073);
user_pref("services.settings.main.sites-classification.last_check", 1578701073);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1578701073);
user_pref("services.settings.security.onecrl.checked", 1578701073);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1578699177);
user_pref("toolkit.startup.last_success", 1578700312);
user_pref("toolkit.telemetry.cachedClientID", "5dab7898-1318-4c38-a012-43192a77d854");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
